name: Metrics

on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"

  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: eshanized
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_crypto: yes
          plugin_crypto_days: 1
          plugin_crypto_precision: 2
          plugin_crypto_vs_currency: usd
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_self: yes
          plugin_notable_types: commit
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://snigdhaos.org
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_thanks: iconized
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: relative
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          # plugin_skyline: yes
          # plugin_skyline_compatibility: yes
          # plugin_skyline_frames: 120
          # plugin_skyline_quality: 1
          # plugin_skyline_settings: '{"url": "https://skyline.github.com/${login}/${year}", "ready": "[...document.querySelectorAll(\'span\')].map(span => span.innerText).includes(\'Share on Twitter\')", "wait": 1, "hide":"button, footer, a"}'
          # plugin_skyline_year: current-year
          plugin_traffic: yes
